#===============================================================================
#             Texas Instruments OMAP(TM) Platform Software
#             #  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
##  Use of this software is controlled by the terms and conditions found 
#  in the license agreement under which this software has been supplied.
#  #===============================================================================

SUBDIRS = catchall_apps

all: $(SUBDIRS)

catchall_apps:
	make -C apps

install:
	make -C apps install

clean:
	make -C apps clean
