#===============================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found 
#  in the license agreement under which this software has been supplied.
#===============================================================================

SUBDIRS = timer_apps

all: $(SUBDIRS)

timer_apps:
	make -C timer

install:
	make -C timer install

clean:
	make -C timer clean
