# Monterrey LBP Team - Test Team
# Misael Lopez Cruz
# Compile akey utility

CFLAGS += -Wall
TARGETS=akey waitkey choice

all: $(TARGETS)

install:
	mv $(TARGETS) $(UTILS_BINARIES)

clean:
	rm -f *.o $(TARGETS)
