#===============================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found
#  in the license agreement under which this software has been supplied.
#===============================================================================

OBJS := install

all: $(OBJS)

install:
	mkdir -p scripts/test
	mkdir -p scripts/tmp

clean:
	rm -rf scripts/log*
	rm -rf scripts/tmp
	rm -rf scripts/test
