#!/bin/sh

set -x

operation=$1

if [ "$operation" = "create" ]; then

  size=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerCmdDd.sh "1" "/mnt/$to/file.$to" "$size"
  wait   

elif [ "$operation" = "copy" ]; then

  from=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerCmdCp.sh "1" "/mnt/$from/file.$from" "/mnt/$to/file.$from"
  wait

  cmp /mnt/$from/file.$from /mnt/$to/file.$from

elif [ "$operation" = "readwrite" ]; then

  from=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerCmdCp.sh "1" "/mnt/$from/file.$from" "/mnt/$to/file.$to.rw" &
  $UTILS_DIR_HANDLERS/handlerCmdCp.sh "2" "/mnt/$to/file.$to" "/mnt/$from/file.$from.rw" &
  wait

  cmp /mnt/$from/file.$from /mnt/$to/file.$to.rw
  cmp /mnt/$to/file.$to /mnt/$from/file.$from.rw

elif [ "$operation" = "remove" ]; then

  from=$2
  rm /mnt/$device/file.$device

fi

# End of file