#!/bin/sh

set -x

operation=$1

if [ "$operation" = "create" ]; then

  size=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerStatistics.sh "dd if=/dev/urandom of=/mnt/$to/file.$to bs=1M count=$size" "1"

elif [ "$operation" = "copy" ]; then

  from=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerStatistics.sh "cp /mnt/$from/file.$from /mnt/$to/" "1"

  cmp /mnt/$from/file.$from /mnt/$to/file.$from

elif [ "$operation" = "readwrite" ]; then

  from=$2
  to=$3

  $UTILS_DIR_HANDLERS/handlerStatistics.sh "cp /mnt/$from/file.$from /mnt/$to/file.$to.rw" "1" &
  $UTILS_DIR_HANDLERS/handlerStatistics.sh "cp /mnt/$to/file.$to /mnt/$from/file.$from.rw" "2" &
  wait

  cmp /mnt/$from/file.$from /mnt/$to/file.$to.rw
  cmp /mnt/$to/file.$to /mnt/$from/file.$from.rw

elif [ "$operation" = "remove" ]; then

  from=$2
  rm /mnt/$device/file.$device

fi


# End of file