#!/bin/sh

set -x

operation=$1

if [ "$operation" = "setup" ]; then
  $MMCSD_DIR_HELPER/handlerMmcsdBlock.sh "create" "1" "dos" /mnt/mmcsd/
elif [ "$operation" = "cleanup" ]; then
  $MMCSD_DIR_HELPER/handlerMmcsdBlock.sh "remove" "1" /mnt/mmcsd/
fi

# End of file