#!/bin/sh

set -x

operation=$1

if [ "$operation" = "setup" ]; then
  time $MTD_DIR_HELPER/handlerMtdBlock.sh "create" "nand" /mnt/nand/
elif [ "$operation" = "cleanup" ]; then
  time $MTD_DIR_HELPER/handlerMtdBlock.sh "remove" /mnt/nand/
fi

# End of file