#/* ================================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found
#  in the license agreement under which this software has been supplied.
# ================================================================================ */

SUBDIRS = testusb evtest microcom gadgetfs

all: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@

install:
	$(foreach folder,$(SUBDIRS),$(MAKE) -C $(folder) install)

clean:
	$(foreach folder,$(SUBDIRS),$(MAKE) -C $(folder) clean)
