###########################################################################
#(C) Copyright Texas Instruments, 2007. All Rights Reserved.
#
# Name of the file: Makefile
#
# Location of the file:
#
# Brief description of the contents of the file:
#       Makefile for OS-Kernel tests
#
# Detailed description of the contents of the file:
# This Makefile is used to compile MMC test programs.
#
# Author: Ricardo Perez Olivares (x0081762@ti.com)
#
# Created on: 27 Oct 2009
#
# Change Log:
#############################################################################
