###############################################################################
# (C) Copyright Texas Instruments - All Rights Reserved
#
# Name of the file: Makefile
#
# Top Makefile for USBDevice Test Suite
###############################################################################
OBJS := install

all:$(OBJS)

install:
	mkdir -p scripts/test
	mkdir -p scripts/tmp

clean:
	rm -rf scripts/log*
	rm -rf scripts/tmp
	rm -rf scripts/test
