###########################################################################
# (C) Copyright Texas Instruments, 2008. All Rights Reserved.
#
# Name of the file: Makefile
#
# Brief description of the contents of the file:
#       Makefile for Utils Power and Performance
#
# Detailed description of the contents of the file:
# This Makefile is used to compile utils directory to support
# all Power and Performance testsuites
#
# Author: Ricardo Perez
#
# Created on: Fri Oct 10 11:34:05 CDT 2008
#
# Change Log:
#
############################################################################
OBJS := install

all:$(OBJS)

install:
	mkdir -p bin
clean:
	rm -rf bin
