# ================================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found
#  in the license agreement under which this software has been supplied.
# ================================================================================

SUBDIRS=omap3_app

all: $(SUBDIRS)

omap3_app:
	make -C omap3

clean:
	make -C omap3 clean

install:
	make -C omap3 install
