
TOPDIR = .

TARGET = $(CROSS_COMPILE)fbtest

OBJS += drawops/drawops.o fonts/fonts.o images/images.o visops/visops.o \
	tests/tests.o

SUBDIRS = drawops fonts images visops tests

include $(TOPDIR)/Rules.make

