#/* ==========================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found
#  in the license agreement under which this software has been supplied.
# ========================================================================== */

SUBDIRS = nuttcp-6.1.2_dir

all: $(SUBDIRS)

nuttcp-6.1.2_dir:
	make -C nuttcp-6.1.2

install:
	make -C nuttcp-6.1.2 install

clean:
	make -C nuttcp-6.1.2 clean
