#/* ================================================================================
#             Texas Instruments OMAP(TM) Platform Software
#  (c) Copyright Texas Instruments, Incorporated.  All Rights Reserved.
#
#  Use of this software is controlled by the terms and conditions found 
#  in the license agreement under which this software has been supplied.
# ================================================================================ */

SUBDIRS = dma_apps

all: $(SUBDIRS)

dma_apps:
	make -C dma

install:
	make -C dma install

clean:
	make -C dma clean
