###########################################################################
# (C) Copyright Texas Instruments, 2008. All Rights Reserved.
#
# Name of the file: Makefile
#
# Brief description of the contents of the file:
#       Makefile for NAND/OneNAND Power and Performance TestSuite
#
#
# Detailed description of the contents of the file:
# This Makefile is used to enabled NAND/OneNAND PPM
#
# Author: Ricardo Perez
#
# Created on: Fri Oct 10 11:34:05 CDT 2008
#
# Change Log:
#
############################################################################
OBJS := install

all:$(OBJS)

install:
	mkdir -p bin
	mkdir -p scripts/test
	mkdir -p scripts/tmp
clean:
	rm -rf scripts/log*
	rm -rf bin
	rm -rf scripts/tmp
	rm -rf scripts/test
